[firebase]
type = "service_account"
project_id = "streamlitfire"
private_key_id = "ea0232c31d31e13ebb71195193d0735a44bd45a2"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDq+hXW9QoRnsJT
+zTKXQk4gmFWAcmmwxweeYQ+K8uh0mhMe+8iFzmQsTOdf9NBtPfW8IY88uZW+y8s
AQk1bF/mQAYRBS3CQMtyfJtxlMBbGapfTOj6Qh7bPQqcqxwkmDFCHyVlIBjAAvic
ebGT5lv1xJcyOwbZ/PTymzJTWJMFlmK0pX5Fb0FpxPOkn60XjuccjQowsbXQlrio
Sd71c5FOsKWkhESy/6HyiUYgJx1Fk7OTWHDrAkprTzmW6RzpOQNWqifdlbgLeb52
UtnYwCH/Npg7VY0NrMA3nyHxMxnMP83/OfPs6vPB1kujX2Sp6PUKl/fPJgKM0Jue
MKdJqqSRAgMBAAECggEAEssUGn0lF2oUxy+J3Ivt90Pcq33sT7CLLzGVqHzlBhKu
BNZktqh+eI2zplHy5rs/ZBF/EW2ovowyDNlVKZ169HXQ0zIQcHJ+OX0XcZ4g3fU1
8Y+7knuqiOssGuh6978ayw8MQdCvXUWsXKRFb6IDX0S57J2/KCNZjY3PS85pwKh/
OxJc5Fg2SZnhQttBZdbLdFGyfa3E7LAaovk18SCuZbXuJ86Ne2BfyO5/nQrrBJwm
t5aNhhbO8yqy7QT+BSP+jGboAPLJyshCvJuca+0uU9G8kvzuX6USzQ7UK0UQvTcy
7fjeeAWWtnjmNRKJIoe8h79kEoDq4OY9Yzp5rEFngQKBgQD90EFGnZsX3iC8mdhi
nnsLrTIcxB6lR1cRuGYpd6EaVw2I7bK1Axwzt6/DglZiShkfDnzKD9TJ1typlrzv
ZWdNJTBpoGjtOi+B5zzxnaCSibO0lKSMbJv1Jp3HdMx8dC7xrBdTGUQPloryDHzI
/PpMkoixMGEkUZahlBy3qk9MHwKBgQDtAEoKeSlx+YD9D/MoCT517hZ0BMlTYrZi
zSlyaGZWJa/lL6JCnvUr0mBwPGb/nasZ9nTgiMIy4ubbHGL28b9m75FwpiR0Cjwi
sJynyOBjVkAij5C9l60eQ5AkEsSVGwnSEdsQ14Rp1OLMj2zauYyOFNwPq6dNG3IC
9EhJoNj5TwKBgCGO3GKSygPA2cE18hcv7wLfNmX5RDgEE64DHHbVG1bZNa/qBZvL
OnpYCgQmgndiZqnlh3hL2Y2KPAisJnTcimj3xsvgap8a91cMlNE5Txaw4DK7CHqM
jZ4/KdNKTRMTZXWMlFTnXUlWVS6lmgYU9J8VLL+Irv9XTjw00gsymGNvAoGAOZ8+
YTmAKCPfhqegGPXWZ9nRP7gCMvHnIjJ7h0N2zi8viut/6e638UWfCOrGqBNvjEpt
tEHL5Y9hTZijPyMbxC0vEVJzvnrWkCCclfazB7Pqt/xr1ozQHHGU1BB0F0SRqK+K
sZeUrB6EXfPpJWzDja/oqS606HxpxeoawTwIROUCgYBf2mO7Ax4iZrocfw1BQt6z
ENefc1cO8s/0purMTvn74MqzdLU1KwQXTglZGhruYUMaPivt7N5JFEzG0Y9F9/M8
DjcPWGcN+tG+Z9f+4CjN5E1SBo1uZtN1F2QVwNQ5xTunoPJ47UE0GTZv1iSU/K9s
0F0X5X2lvd7adhL6lCbsZg==
-----END PRIVATE KEY-----'''
client_email = "firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"
client_id = "109398503127320900742"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
