[firebase]
type = "service_account"
project_id = "streamlitfire"
private_key_id = "dc55678b86efaf23019c63daf7fd810107230176"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYe2MxwJHj+hPX
Uav1ItqGx4pQMUu9AtBMcnLr21jZmKHelYOShpsSXqevOOCLmDlHEWVyuZPstHH3
SbTsx+Thr60d5I9LN+XH6iIB5gNCjYfvgt5+9mUsiT77n7kDJES6kXHuQ7ouCtW2
pZEKobou5NtzVT0WF7atUeYWbBgOwtpOD1IkxPzQwhUpVuhex542HBi7Paw65orE
v55R1G6lNt3qss5KY2UFgXhkR+ovYx50SAoMP4TIexavT8o3NU4sOv7tJtaQ89hl
XOX3/o++Z/NCQ6v2siYwAiq1QJbG90Gi6qOTbUTPoErajVyCx1XEtDeoywTe/zEc
HVX28QpVAgMBAAECggEAIjM4lCnkPv0x8o8xsa2D1IuQWPy5h1cId8EKyB5eTw3W
Lomb5WM2CFh9JUatTHoTzL4Y4jK//C0by7J3N019Z2ZC/qurPRx4OA7qWkEoFYcP
iHeypkjm9+Z/nynbshnyJWNmaaG8skOBXDJF9hvAmfCATR2+8gPXGAhAwmIzwil2
7UtXHaQdW2iUmE/zlJXqaC3Kw9F5YmfpNXo0VQZn4+JM4F7fT/cSR7Z8zDjdB8bZ
PLWmYyHcGrA/xNGQ/jKsk+Fed6ZfAZ7fxAzvNMCtaf9/RtObBXj2YBxS+fvkzUMt
IK03FWLzpnL/Ud/TEvIXtZXx+PimffdBBCQBdU/RiQKBgQDKBeh5noCzQay7kblE
SZDl0xYoN2C0MG9H9xG7f96AF/luwqjNn5KgFBMmxlc7/klnTY/gdaYXkxKl8vio
ossqC1US6/XQaYVmvHUWj6WwlxEw30dZ1PV1HLZnvpRjiA/DrJB0/rPboS+hpQdz
tfr/KE+8OVQDYm8o8Y2NXVr8nQKBgQDBOPBOJaprFYNbbnYYhBMOnG5ckeD2Woe1
TlBy7HRqfJHXB8Ej46iVEhb3DiJ3zLV4M1xkbD532mz9ss2+wNOUo2nZgjlZtydL
IgQnhRXZJYDJpvLd3dU7uMKwRnzH0VHaQpw+lZgtKesIfBgOL+eR1bN3Zpbfg9Ic
wO4E4SArGQKBgQCHQ31sMNwrKYXl8KQDPN5vgu4K70koXGWl4Z9V0z++tE6mAl/T
jUw3MjnAdHxkBtZO/Heg6iTTE/4gbpZfEuDEveGwUZy8dmqDZxteh7+AhSVVe6ni
U9wlFZxrygbAvZEQirIOI5t5Kmsh58UdjHMJ9IuukxPVUErtNw534FHTYQKBgFRZ
B8YFeURvyrziFpmTJkKNlTvBzsOcN3u1KTdR82v83ylQUEbbfd89W1sUB4Xmjh1f
xmhsPETTzBpfsKMhx/st7uoth92bL4MD4W5jEWuOjI762zBxQ0Fj4VFUI+qSfLnb
tBs58IlesCQvD805qkwmTsbDuP7vq4wzyHPG1uUZAoGAepyP17cbxYxcRCK9R/Nu
H7PAT1mVr0sJwbz7uj0vbIrmL/9YRh4lI+HP8E9ic+iTtetHVkWwiNUtTCdRO/1v
FZSn1ZLxRv3xHdRwUY0ys2T7FIstkYEwcl7YFT5DBmfdz5bqWTMeM/J6gRANlfIj
nmhgp1RJljzuBXbq9LxlHhU=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"
client_id = "109398503127320900742"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"


