[firebase]
type = "service_account"
project_id = "streamlitfire"
private_key_id = "ea0232c31d31e13ebb71195193d0735a44bd45a2"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDq+hXW9QoRnsJT
+zTKXQk4gmFWAcmmwxweeYQ+K8uh0mhMe+8iFzmQsTOdf9NBtPfW8IY88uZW+y8s
...
-----END PRIVATE KEY-----'''
client_email = "firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"
client_id = "109398503127320900742"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-r6lno@streamlitfire.iam.gserviceaccount.com"
